### ISSUE TITLE
Not detecting :( PS2020

### ISSUE THREAD

**Issue by Phantom0013** [lolitee/adobe-discord-rpc#11]
![image](https://user-images.githubusercontent.com/77114925/106923246-e18c6680-6733-11eb-964a-6f8a1257c143.png)

![image](https://user-images.githubusercontent.com/77114925/106923078-b6a21280-6733-11eb-898a-d1b461db2848.png)

cant understand what's the issue discord's not detecting it tried with PS 2020

**Comment by lolitee** [comment]
u have to add a layer it will send an event to node

**Comment by lolitee** [comment]
by any chance do u have disabled home screen? its basically this thing 
![image](https://user-images.githubusercontent.com/62479501/107025463-c52b1100-67a9-11eb-9baa-b17102fda8b2.png)

**Comment by Phantom0013** [comment]
yes i had that homescreen disabled but turned it back on and started adding layer and working on the file but still not showing in discord

**Comment by lolitee** [comment]
try deleting the adobe discord rpc folder in %appdata%

**Comment by Phantom0013** [comment]
![image](https://user-images.githubusercontent.com/77114925/107160782-5d014880-69be-11eb-8c7b-74cd5b00bbbf.png)
there was no discord rpc folder here

**Comment by lolitee** [comment]
oh no its in roaming, there should be adobe discord rpc or adobe rpc one of them, inside of that folder should be a config.json

**Comment by lolitee** [comment]
![image](https://user-images.githubusercontent.com/62479501/107219402-505a1000-6a11-11eb-860f-80e16e120605.png)

**Comment by lolitee** [comment]
by any chance did u enable debug mode? the one that is in regedit

**Comment by Phantom0013** [comment]
> oh no its in roaming folder, there should be adobe discord rpc or adobe rpc one of them, inside of that folder should be a config.json, also can you try to open localhost:6767 in browser while ur photoshop is on?

 There's no folders like that under roaming 🤔 
 
 

> by any chance did u enable debug mode? the one that is in regedit

and yes enabled debugmode

**Comment by lolitee** [comment]
oh it probably has issues creating the configuration folder then but i believe it should work without it

**Comment by lolitee** [comment]
can u try extracting the zip and put the folder into roaming?
[adobe-discord-rpc.zip](https://github.com/lolitee/adobe-discord-rpc/files/5950054/adobe-discord-rpc.zip)

**Comment by Phantom0013** [comment]
> can u try extracting the zip and put the folder into roaming?
> [adobe-discord-rpc.zip](https://github.com/lolitee/adobe-discord-rpc/files/5950054/adobe-discord-rpc.zip)

done but still same only difference it made is this show layer,file name and time here but not in discord
![image](https://user-images.githubusercontent.com/77114925/107340605-f8d8a480-6ae3-11eb-94a3-2b514ed36d93.png)

**Comment by lolitee** [comment]
add some layers it will send an event

**Comment by Phantom0013** [comment]
hmmm still same after 30mins 😢

**Comment by lolitee** [comment]
by any chance do u have any apps using the port 6767?

**Comment by Phantom0013** [comment]
> by any chance do u have any apps using the port 6767?

nope i guess dont know how to check that

**Comment by Phantom0013** [comment]
![image](https://user-images.githubusercontent.com/77114925/107817044-91e51500-6d9b-11eb-8f88-9d0e9912103b.png)
hmm so this is what it's showing after opening PS and going to localhost:6767

**Comment by lolitee** [comment]
its supposed to work then if it doesnt then i dont really know

**Comment by lolitee** [comment]
can you try to reinstall photoshop to newer version of it?

**Comment by General-Zimmer** [comment]
Try to remove the "game" from the game activity tab and let this plugin create a new one.

**Comment by ThibeauDS** [comment]
I kinda have the same thing here.
I even can't load up localhost:6767 and there no other active connections on port 6767

**Comment by lolitee** [comment]
if u have done everything correctly try extracting and dragging "adobe-discord-rpc" folder into %appdata% [here](https://cdn.discordapp.com/attachments/819529494015639593/819529506884026418/adobe-discord-rpc.zip), if it still doesnt work then try updating ur adobe product in most cases it helped

**Comment by ThibeauDS** [comment]
it's not in %appdata%
since the CEP folder wasn't there, it was in Program Files/Commen Files/Adobe/...

Even when I followed those other 2 tutorials (then it was port 8088), the localhost didn't work too.
I added that config file to the root of the existing adobe-discord-rpc folder, but nothing...
I do have to mention, Hyper-V and virtualization (for virtualbox) is on.

**Comment by lolitee** [comment]
cep folder is located in Program Files (x86)\Common Files\Adobe\CEP\extensions

**Comment by ThibeauDS** [comment]
I moved it to that dir but still the same :/

**Comment by lolitee** [comment]
oh ye it might b better to talk about it on my discord server https://discord.gg/RGtxbuFtzb  just open a ticket

**Comment by ThibeauDS** [comment]
aye
