### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by nolemretaWxd** [lolitee/adobe-discord-rpc#12]
Discord doesn't show rich presence. None of buttons on config window work. I've enabled debug mode and here's my .debug file
Tried in Premiere 2020
```    <ExtensionList>
        <!-- 1 -->
        <Extension Id="com.discord.rpc.tee">
           <HostList>
                <Host Name="PHSP" Port="8088"/>
                <Host Name="PHXS" Port="8088"/>
                <Host Name="ILST" Port="8088"/>
                <Host Name="PPRO" Port="8088"/>
                <Host Name="PRLD" Port="8088"/>
                <Host Name="AEFT" Port="8088"/>
                <Host Name="FLPR" Port="8088"/>
                <Host Name="AUDT" Port="8088"/>
                <Host Name="DRWV" Port="8088"/>
                <Host Name="RUSH" Port="8088"/>
            </HostList>
        </Extension>
    </ExtensionList>

**Comment by lolitee** [comment]
does localhost:6767 work in browser it should look like this 
![image](https://user-images.githubusercontent.com/62479501/108773702-0ae42980-755f-11eb-9c57-c7de9b088633.png)

**Comment by nolemretaWxd** [comment]
> does localhost:6767 work in browser it should look like this also what version of the extension are u running
> ![image](https://user-images.githubusercontent.com/62479501/108773702-0ae42980-755f-11eb-9c57-c7de9b088633.png)

![image](https://user-images.githubusercontent.com/31414969/108838611-2b020000-75d4-11eb-9788-ccdb40467871.png)

**Comment by lolitee** [comment]
by any chance, have u done the thing in regedit, which is changing regedit > HKEY_CURRENT_USER/Software/Adobe/CSXS.10 or (9)/PlayerDebugMode 1

**Comment by nolemretaWxd** [comment]
> by any chance, have u done the thing in regedit, which is changing regedit > HKEY_CURRENT_USER/Software/Adobe/CSXS.10 or (9)/PlayerDebugMode 1

yeah

**Comment by lolitee** [comment]
use the cefclient to debug, normally it doesnt work with browser client

**Comment by lolitee** [comment]
if it doesnt work then we can try resolving it together on discord

**Comment by nolemretaWxd** [comment]
> if it doesnt work still then we can try resolving it together on discord

add me on discord: nolemretaW ッ#2137

**Comment by lolitee** [comment]
resolved

**Comment by ScarVite** [comment]
@lolitee it appears i have the same issue, i've set PlayerDebugMode to "1", The Extension Shows up in Window->Extension but if i click on it nothing happens.

And i can't connecto to 127.0.0.1:6767.

My Discord is: ScarVite#6606

**Comment by lolitee** [comment]
https://discord.gg/RGtxbuFtzb
