### ISSUE TITLE
extension window opens but can't interact with toggles 

### ISSUE THREAD

**Issue by fliboys** [lolitee/adobe-discord-rpc#13]
clicking the extension in premiere opens up the window, but the toggles don't function and seems like it's just a static page. Discord displays the game as the project file name but none of the other functions like app icon work. using latest version of PP 2020. previously had older version but removed since it didn't work with 2020 version and was causing the app to lag. would love to use this :(

**Comment by lolitee** [comment]
uhh can we solve this on discord? it would b prob better than commenting it here

**Comment by fliboys** [comment]
sent you a request :)

**Comment by lolitee** [comment]
fixed
