### ISSUE TITLE
I am getting a unsigned extension error

### ISSUE THREAD

**Issue by Trimpsuz** [lolitee/adobe-discord-rpc#14]
I added the registery entry "PlayerDebugMode" of type "string" and of value "1" to the "HKEY_CURRENT_USER/Software/Adobe/CSXS.8" registery key, and I am still getting a "unsigned extension" error. Any help?

**Comment by lolitee** [comment]
im not sure if 2018 works with the extension, it would be prob the best to go at least 2020

**Comment by Trimpsuz** [comment]
Sorry for the late reply, I am using 2021, but I only changet is for "CSXS.8", changing it for the others fixed it. Thanks!
