### ISSUE TITLE
Doesn't show in dc

### ISSUE THREAD

**Issue by Trimpsuz** [lolitee/adobe-discord-rpc#15]
So the old issue was fixed, thanks, but i have a new issue now. Everything works as expected, i can interact with the toggles and localhost:6767 shows "com.discord.rpc.tee PHXS", but nothing shows in dc.

**Comment by Trimpsuz** [comment]
Using Ps 2021 v 22.2

**Comment by lolitee** [comment]
give it some time, do some work in it, when u add for example a layer or rename the project file it should send an event to rpc

**Comment by lolitee** [comment]
https://files.loli.support/i/crl87.mp4 prob like this

**Comment by Trimpsuz** [comment]
I got it to work now, weird
