### ISSUE TITLE
Does this work on macOS?

### ISSUE THREAD

**Issue by SwiftWinds** [lolitee/adobe-discord-rpc#16]

**Comment by lolitee** [comment]
i have no idea it will prob work or it wont u, u can give it a try

**Comment by lolitee** [comment]
actually let me setup a vm to test it

**Comment by lolitee** [comment]
well i couldnt test it in a vm somehow it doesnt work most likely due to my cpu being amd

**Comment by SwiftWinds** [comment]
OK, when I get the time, I'll see if I can test it myself.

**Comment by lolitee** [comment]
the extension now has macos support

**Comment by SwiftWinds** [comment]
Awesome!
