### ISSUE TITLE
Add a default .debug file.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [lolitee/adobe-discord-rpc#20]
Hello there,

As the current .zxp method is currently broken, we need to install it as a debug extension.

In the linked documentation on how to activate debug mode, it lists how to allow the extension to connect to the internet via the `.debug` file.

I've been wondering, to simplify the install process, why won't that file be already present in the releases versions?

Or, in the case to prevent unwanted of default port 8088 for those few, creating a renamed `.debug` file like `REMOVE.debug` with the instruction on how to change the default port, and activate it as comments in that same file.

**Comment by lolitee** [comment]
you create a string key called PlayerDebugMode and the value of 1 into it. depending on your adobe version
2021/2020(late): HKEY_CURRENT_USER/Software/Adobe/CSXS.10
2020(early)/2019/HKEY_CURRENT_USER/Software/Adobe/CSXS.9

**Comment by PoorPocketsMcNewHold** [comment]
No, I've managed to do it, don't worry.

What I meant, is that for other users, adding a `.debug` file already in the release zip might be easier for users, as they just need to edit the already made `.debug` file if needed.

Ne, podařilo se mi to, nebojte se.

Chtěl jsem tím říct, že pro ostatní uživatele by mohlo být přidání souboru `.debug`, který je již v release zipu, jednodušší, protože v případě potřeby stačí upravit již vytvořený soubor `.debug`.

**Comment by lolitee** [comment]
the .debug file is also for debugging the extension in browser which is useless

**Comment by PoorPocketsMcNewHold** [comment]
Oooh, alright. Then, quite a useless issue I've done. Thanks for the answer!
