### ISSUE TITLE
Discord status doesnt show anything

### ISSUE THREAD

**Issue by daqnxdev** [lolitee/adobe-discord-rpc#23]
Yes, my game activity is on. I also have the extension open in Premiere Pro. Why is it not doing anything? It just shows the default user example.

![image](https://user-images.githubusercontent.com/71961959/123847000-f1d4f600-d90d-11eb-8fff-e4bd904a8e1f.png)

**Comment by fevilelis1** [comment]
did you find any fixes? i am getting this kind of problem too

**Comment by lolitee** [comment]
try using the rewritten version here https://cdn.discordapp.com/attachments/847588172203425802/847596109777076234/discord_rpc.zip , same installation process

**Comment by daqnxdev** [comment]
Alright, I'll try, thanks.

**Comment by lolitee** [comment]
u can also join the support discord server it would b prob easier for us to solve the issue

**Comment by daqnxdev** [comment]
It is not working still, I'll join.
