### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fevilelis1** [lolitee/adobe-discord-rpc#24]
![image](https://user-images.githubusercontent.com/63804095/123850287-394c8980-d8f0-11eb-80db-886275e7c42b.png)

help??!@

**Comment by fevilelis1** [comment]
i fixed it, but now i cant disable anything
![image](https://user-images.githubusercontent.com/63804095/123855112-e1b11c80-d8f5-11eb-9434-6d3c9aad5bd6.png)

**Comment by lolitee** [comment]
you need to enable debug mode in regedit https://github.com/lolitee/adobe-discord-rpc/blob/master/GUIDE.md

**Comment by lolitee** [comment]
the extension now doesnt require a server, u should give it a try, it might work
