### ISSUE TITLE
It doesn't do anything, it doesn't give you the status

### ISSUE THREAD

**Issue by HackCreep16** [lolitee/adobe-discord-rpc#25]

**Comment by HackCreep16** [comment]
it only gives me this, I already added the registry keys that needs to be added
![image](https://user-images.githubusercontent.com/80411370/123939398-acc2c980-d9ca-11eb-88b9-49c1eca1f8e7.png)

**Comment by lolitee** [comment]
you can join my support discord it would b prob better for us to solve this https://discord.gg/RGtxbuFtzb

**Comment by lolitee** [comment]
the extension now doesnt require a server, u should give it a try, it might work

**Comment by vilxoro** [comment]
i also have this problem

**Comment by lolitee** [comment]
join the discord aerver @vilxoro
