### ISSUE TITLE
It wont show if we have "Group" in our project (Photoshop)

### ISSUE THREAD

**Issue by WatanabeDaiki135** [lolitee/adobe-discord-rpc#26]
If we have "Group"  in our project, it won't show up, but when we delete that "Group", it's back
![preview](https://user-images.githubusercontent.com/87174986/125053997-92d45700-e05a-11eb-89ac-6fb47fa3d546.png)

**Comment by lolitee** [comment]
are u using version 14 or 13 because i cant seem to be able to reproduce it on 14

**Comment by WatanabeDaiki135** [comment]
I'm using Photoshop 2021 also known as version 22.1.-

**Comment by WatanabeDaiki135** [comment]
Picture taken on different account and different device

If I look at my account on my device, yes it show that I'm opening photoshop, but on other people, it's not showing anything

**Comment by wertos97** [comment]
I was able to reproduce the problem on 0.0.13.1-alpha and 0.0.1-beta. It works perfectly on the same pc's discord app but for web client with different account logged in and mobile client with the same account it won't show up. As mentioned by WatanabeDaiki, the problem occurs when a group or a layer within a group is focused but also when working inside workspaces. Using just layers makes it work but only for another account on web client. Discord Android app won't show anything no matter what I do making me believe it's more of Discord's problem.

**Comment by lolitee** [comment]
okay so, the bug is due to the party size for some reasons, if u are on browser or on phone and the party size of the user is bigger than party max then it wont be able to handle the issue somewhat and crashes rpc for them 
![image](https://user-images.githubusercontent.com/62479501/125414599-9d707175-ca61-424e-a6a4-cd9b7fd28516.png)

**Comment by lolitee** [comment]
okay i have a possible fix coming soon

**Comment by lolitee** [comment]
possible fix here https://github.com/lolitee/adobe-discord-rpc/releases/tag/v0.0.2-beta

**Comment by wertos97** [comment]
Now it won't work at all for me. Panel switches are unclickable and no rpc is shown, even in desktop client.

**Comment by WatanabeDaiki135** [comment]
Ummm I tested the beta release and same as above, now it won't work at all, I can't click the panel switches

**Comment by lolitee** [comment]
oh jquery stopped working thats mb on my side

**Comment by lolitee** [comment]
I have reuploaded the release there it should be available https://github.com/lolitee/adobe-discord-rpc/releases/tag/v0.0.2-beta

**Comment by WatanabeDaiki135** [comment]
Umm, I don't know is it me or something, but It's still won't show the RPC for me  ( ´。＿。｀)

**Comment by wertos97** [comment]
0.0.3-beta didn't fix the problem for me. It still shows nothing as in 0.0.2-beta

**Comment by lolitee** [comment]
the crash was bcs the extension couldnt find a profile bcs it didnt create one before so ye ill upload the fix soon but im still looking into photoshop because the party counting is still wrong

**Comment by lolitee** [comment]
i just updated the extension give it a try

**Comment by wertos97** [comment]
v0.0.3.1-beta fixed the problem for me, now it's working perfectly. Thank you!

**Comment by WatanabeDaiki135** [comment]
Oh my god, I'm so sorry for the late reply, and yes the bug fixed  with this new patch, and it works perfectly
Again thank you (～￣▽￣)～
![color](https://user-images.githubusercontent.com/87174986/125880786-d6915091-a32d-42e5-9783-7cd212c53d93.PNG)

**Comment by WatanabeDaiki135** [comment]
I'm gonna close this... and again thank you
