### ISSUE TITLE
File state can still be read even if it's off

### ISSUE THREAD

**Issue by wertos97** [lolitee/adobe-discord-rpc#28]
Even if I choose to hide the file state which shows the name of the layer I am working on, it still can be seen when hovering over small icon showing used tool.

![image](https://user-images.githubusercontent.com/18363190/126759663-0bdfc306-3a78-473d-9bbe-f7caa2ad1026.png)

![image](https://user-images.githubusercontent.com/18363190/126759696-9e5be318-da6c-4b14-b584-e15e666c1ad2.png)

**Comment by lolitee** [comment]
ill look into the issue tomorrow since ill have some time

**Comment by lolitee** [comment]
should be fixed in this version sorry if it took ages i was busy with some stuff https://github.com/lolitee/adobe-discord-rpc/releases/tag/v0.0.3.3-beta
