### ISSUE TITLE
Dreamweaver Integration Does Not Function

### ISSUE THREAD

**Issue by amprf144** [lolitee/adobe-discord-rpc#29]

**Comment by lolitee** [comment]
its because i didnt add stuff into it, will do today if i got spare time

**Comment by lolitee** [comment]
okay so basically dreamweaver doesn't rly support invisible extension or with whatever reasons it doesnt autostart so in conclusion ill have to rewrite lots of stuff

**Comment by lolitee** [comment]
its also the only app that does that or im just stupid

**Comment by lolitee** [comment]
okay so this is a bug on adobe's side but im able to do it with other method which should work im gonna push update on this soon

**Comment by lolitee** [comment]
here it is, please give it a try! https://github.com/lolitee/adobe-discord-rpc/releases/tag/v0.0.4-beta

**Comment by ImAARIX** [comment]
Hi!
It work for me on the last version of Dreamweaver 2021.
Just have to go to: Window->Extension->Discord Rich Presence.

**Comment by lolitee** [comment]
if more people confirms the functionality, ill close the issue

**Comment by lolitee** [comment]
tested on a freshly installed windows everything works
