### ISSUE TITLE
Works on photoshop but doesn't on everything else

### ISSUE THREAD

**Issue by TheCakeFactory** [lolitee/adobe-discord-rpc#31]
It works fine on Photoshop but it seems it's not working for Premiere pro and After Effects 

**Photoshop**
![drc psp](https://user-images.githubusercontent.com/90282274/132400338-ef1d7272-3c7a-44a5-9431-05211301d8e0.png)
**Premiere Pro**
![drc prp](https://user-images.githubusercontent.com/90282274/132400368-e0582d0f-a0ad-4b5b-9399-b5341ee3444d.png)
**After Effects**
![drc ae](https://user-images.githubusercontent.com/90282274/132400525-f9ca0483-612e-4a79-824b-226176ec6a88.png)

**Comment by lolitee** [comment]
can u create a ticket in my discord server, https://discord.gg/RGtxbuFtzb
