### ISSUE TITLE
Not working with any of the latest Adobe Applications?

### ISSUE THREAD

**Issue by Ka0tik** [lolitee/adobe-discord-rpc#32]
Using the latest Creative Cloud apps, it no longer works for me. I have uninstalled and re-installed multiple times. Shows up in the extentions menu for all apps but nothing loads when clicked.

Any ideas please?

Thanks!

**Comment by lolitee** [comment]
can u join the discord server, would b prob better for us to troubleshoot the issue https://discord.com/invite/RGtxbuFtzb

**Comment by lolitee** [comment]
also i feel like when u updated ur adobe apps they all now use csxs 11 so check in regedit if thats the case, if so then just create a string value in there

**Comment by Ka0tik** [comment]
> 
> 
> also i feel like when u updated ur adobe apps they all now use csxs 11 so check in regedit if thats the case, if so then just create a string value in there

That fixed it, thank you for the fast response and great tool!
