### ISSUE TITLE
Cannot disable the rich presence

### ISSUE THREAD

**Issue by Suraf** [lolitee/adobe-discord-rpc#36]
**Describe the bug**
Cannot disable the presence for a certain program. e.g. Audition.

**To Reproduce**
1. Open an Adobe program like Audition.
2. Window > Extensions > Discord Rich Presence
3. Turn the "enabled" setting off.
4. See if the rich presence is still present or restart the program.
5. After restarting, see if the rich presence is still there.

(Still there for me and verified that the enabled setting is still turned off.)

**Expected behavior**
Turning off the "enabled" setting for the rich presence should no longer display this program on Discord's Rich Presence.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version 22000.258

**Additional notes**
I'd like to have the rich presence to display for when I'm using Photoshop or Illustrator but I also use Audition for my Virtual Audio cables and I'd rather not display the rich presence for Audition.

![image](https://user-images.githubusercontent.com/19893933/137645492-cda724be-f8e5-4eb3-b377-644f39b229a5.png)
![image](https://user-images.githubusercontent.com/19893933/137645501-151948b8-f018-463f-a449-2ed5bf22e53f.png)

**Comment by lolitee** [comment]
the disable button isnt implemented yet thats why

**Comment by lolitee** [comment]
gonna be in the next update
