### ISSUE TITLE
Lightroom support

### ISSUE THREAD

**Issue by Breigner01** [lolitee/adobe-discord-rpc#39]
**Is your feature request related to a problem? Please describe.**
I'd like to use this extension on lightroom.

**Describe the solution you'd like**
Do you plan to integrate lightroom in the extension?

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by lolitee** [comment]
its impossible sorry about it

**Comment by Breigner01** [comment]
Oh that's sad, why's that?

**Comment by lolitee** [comment]
no cep support
