### ISSUE TITLE
"Run Script Error: Uncaught Exception"

### ISSUE THREAD

**Issue by SuperNoahPlushes** [lolitee/adobe-discord-rpc#40]
**Describe the bug**
Opening Premiere causes an error to appear saying "Run Script Error: Uncaught Exception" and clicking OK brings the error back again and again. 

**To Reproduce**
1. Open Premiere with the script installed
2. Error appears

**Expected behavior**
For that to not happen

**Screenshots**
![image](https://user-images.githubusercontent.com/89299730/143817139-0c5fd9b1-9723-4be2-a2c0-08547b932312.png)

**Desktop**
 - OS: Windows 10

**Additional context**
I'm using Adobe Premiere Pro CC 2019
And Photoshop of the same version works fine. It only affects Premiere.

**Comment by lolitee** [comment]
are u using the latest version of the extension

**Comment by lolitee** [comment]
u could also try updating ur premiere to like 2020+ the issue shouldnt appear there

**Comment by SuperNoahPlushes** [comment]
**are you using the latest version of the extension** yes

**u could also try updating ur premiere to like 2020+ the issue shouldnt appear there** 

Premiere 2020+ i've never really liked. personal prefrence i guess. but ill try it out.

**Comment by lolitee** [comment]
ye give it a try im scared that 2019 ignores some of the error catching stuff since its using an older node version

**Comment by fabiolino4k** [comment]
I actually got around this issue by just somehow ignoring the error and it worked
