### ISSUE TITLE
Discord Rich Presence panel shows blank

### ISSUE THREAD

**Issue by cmrsky** [lolitee/adobe-discord-rpc#42]
**Describe the bug**
Discord Rich Presence panel shows blank in Adobe Illustrator and Adobe InDesign. 
Photoshop is good. Haven't tried the others.

It worked the first try in Photoshop, and never worked in the others.

![Screenshot_5](https://user-images.githubusercontent.com/97463693/148801099-722fa365-dae8-405f-968c-8bc3e7b04a64.png)

**Comment by lolitee** [comment]
u need to enable debug mode in regedit its not a bug

**Comment by cmrsky** [comment]
It's enabled. No issues in Photoshop. All other Adobe softwares: Blank panel.

**Comment by lolitee** [comment]
come to my discord server we can solve it now
