### ISSUE TITLE
Rich Presence for Adobe XD ?

### ISSUE THREAD

**Issue by KazukiKazuma** [lolitee/adobe-discord-rpc#44]
As for great part of the time I'm working with adobe programs I'm using Adobe XD, I would be so greatfull if an Adobe XD rich presence could be implemented.

I know Adobe XD doesn't have a plugin tab that works like the ones from the other programs, like the legacy plugin tab for instance. But maybe a plugin using their marketplace, where you just search for it inside Adobe XD itself could be a possibility ? 

Anyways, loving your job, keep it up and thank you so much.

**Comment by lolitee** [comment]
unfortunatelly adobe XD doesnt support cep but ill figure out something in near future after im finished with school
