### ISSUE TITLE
ZXP install not working

### ISSUE THREAD

**Issue by yaboimilo** [lolitee/adobe-discord-rpc#45]
Hi!

(sent this as a ticket in Discord. Sorry for the duplicate post)
Just wanted to raise an issue when installing v0.0.4.4-beta. Tried multiple times to install it using the zxp installer, but it never really did anything. Files weren't present in any of the CEP folders after installing.
Installing it manually worked, but just wanted to make this issue known.

1. Download v0.0.4.4-beta
2. Install using ZXP Installer

**Expected behavior**
Nothing shown in Premiere Pro's Extensions tab and nothing added to the CEP folders.

 - OS: Windows
 - Windows 10 Enterprise 64-bit (10.0, Build 19044)

**Comment by lolitee** [comment]
the zxp thing is really random either it works or it doesnt and most likely i cant fix it, it also depends on if you have pirated adobe or not. manual method is always prefered
