### ISSUE TITLE
CEP Process High CPU Usage

### ISSUE THREAD

**Issue by senhan07** [lolitee/adobe-discord-rpc#5]
When i start opening Photoshop CC 2020 my cpu usage bump up to 100%. The previous version much stable on cpu usage.
![image](https://user-images.githubusercontent.com/34976706/93295300-ded9b500-f816-11ea-8517-12c97830b8a7.png)

**Comment by lolitee** [comment]
ill look on it when i get back home

**Comment by lolitee** [comment]
[server.zip](https://github.com/lolitee/adobe-discord-rpc/files/5233722/server.zip)
hey, can you try replacing the server folder with this one inside of the "discord rpc" folder? it should fix the issue

**Comment by lolitee** [comment]
oh no that one is broken, ill reupload new one

**Comment by lolitee** [comment]
[server.zip](https://github.com/lolitee/adobe-discord-rpc/files/5233905/server.zip)
file

**Comment by senhan07** [comment]
it's now back to normal again :) 👍
