### ISSUE TITLE
Add Lightroom to Rich Presence

### ISSUE THREAD

**Issue by Jakesta13** [lolitee/adobe-discord-rpc#53]
**Is your feature request related to a problem? Please describe.**
No problem, just a feature

**Describe the solution you'd like**
I'd like to be able to display that I'm working in lightroom, doesn't need to show anything like what image name or anything.
Just "Lightroom / xyz duration" is enough.

**Describe alternatives you've considered**
Tried Discord's built-in game tracker and add a new game, but lightroom is not listed.

**Additional context**
None

Edit: I just realized how this project works, and this actually might have to be a lightroom plugin and be an entirely different project. If so I apologize for wasting the time

**Comment by lolitee** [comment]
not possible
