### ISSUE TITLE
No window and Premiere won't show up

### ISSUE THREAD

**Issue by Viniuau** [lolitee/adobe-discord-rpc#7]
After Effects works fine, but there's nothing on the windows tab.
Premiere won't even show.
![Adobe_Premiere_Pro_hc47lMyOwJ](https://user-images.githubusercontent.com/19510529/101912831-08e60d80-3ba1-11eb-9c0a-93d1394722ab.png)
![Adobe_Premiere_Pro_SyBTS5VW1I](https://user-images.githubusercontent.com/19510529/101912834-0a173a80-3ba1-11eb-9d55-d09381e91359.png)
![AfterFX_HPxATNlH9N](https://user-images.githubusercontent.com/19510529/101912963-2ca95380-3ba1-11eb-8faf-4d1f8d171c7b.png)
![AfterFX_PsiJYStrQ7](https://user-images.githubusercontent.com/19510529/101912974-2e731700-3ba1-11eb-8210-a55bb48ee593.png)

http://localhost:6767/ says `com.discord.rpc.tee AEFT`

**Comment by lolitee** [comment]
i just found out that if i put ![](https://files.loli.support/i/sgy6i.png) basically [Placement="'Main:&amp;Window',600.0,'KBSCE Window menu'"], the tab would disappear

**Comment by lolitee** [comment]
can u try replacing the file in ./CSXS/manifest.xml with the one i have attached into the reply?

**Comment by lolitee** [comment]
uhh apparently i cant upload it on github but https://files.loli.support/i/jkc7s.xml

**Comment by Viniuau** [comment]
Worked like a charm! Thanks a lot!
![image](https://user-images.githubusercontent.com/19510529/101928582-8a936680-3bb4-11eb-9505-48f89fa80d1b.png)
