### ISSUE TITLE
Windows getting out of focus

### ISSUE THREAD

**Issue by Viniuau** [lolitee/adobe-discord-rpc#9]
I've noticed that when there are two adobe apps at the same time, one will be getting out of focus. It starts to get annoying when I want to select something and the window just disappears.
![9Lk49XA7E7](https://user-images.githubusercontent.com/19510529/101989162-4c15ae80-3c7d-11eb-86b0-b6cc78eff6bb.gif)

**Comment by lolitee** [comment]
oh it might be because of process.exit(1)

**Comment by lolitee** [comment]
can u replace the js file in ./server/main.js with https://files.loli.support/i/e6kxq.js like before

**Comment by Viniuau** [comment]
Sorry, I don't open GitHub that often, so I missed your response. Apparently, the file is not available anymore. Would you be able to reupload it? I'll try it asap.

**Comment by lolitee** [comment]
try this https://github.com/lolitee/adobe-discord-rpc/releases/tag/v0.0.12.2-alpha

**Comment by Viniuau** [comment]
Alright, it's working again. Thanks.
